### ISSUE TITLE
Rails Version

### ISSUE THREAD

**Issue by mark100net** [jwoertink/jko_api#7]
Any reason this can't work with Rails 5.1.4 (other than the obvious)?

**Comment by jwoertink** [comment]
I have a branch for rails 5.1. I don't have an app running on 5 though, so I haven't really had a chance to get in deep with it. The main issue was rails 5 [ripped this out](https://github.com/jwoertink/jko_api/blob/rails_51/lib/jko_api/class_descendants_builder.rb#L51). Give it a shot though, and let me know what issues you run in to. I'd like to get back on this soon.

```ruby
gem 'jko_api', githiub: 'jwoeritnk/jko_api', branch: 'rails_51'
```

**Comment by mark100net** [comment]
@jwoertink Thanks for your prompt reply.

I tried with the rails_51 branch (still had to change the rails version in the gemspec because I am using Rails 5.1.4).

It is not working for me (though I'm not 100% sure it is do to my Rails version and not something else). I am getting a routing error (i.e. "no route matches...").

My routes file:

    JkoApi.routes self do
      version 1 do
        resources :session, only: %i[ create destroy index ]
      end
    end

Output of `rails routes`:

    Prefix               Verb   URI Pattern                    Controller#Action
    session_index GET   /session(.:format)          api/v1/session#index {:format=>:json}
                          POST   /session(.:format)          api/v1/session#create {:format=>:json}
    session      DELETE  /session/:id(.:format)     api/v1/session#destroy {:format=>:json}

I am adding header `Accept` header as shown in the readme. 

Same routing error for each of GET, POST or DELETE to /session

If I remove the JkoApi block from my routes file and do:

    delete "session" => "api/v1/session#destroy"
    get "session" => "api/v1/session#index"
    post "session" => "api/v1/session#create"

..everything works.

Any suggestion?

**Comment by jwoertink** [comment]
You should be able to do a curl call to your app.

```
curl -H "Accept: application/vnd.api.v1+json" -H "BEARER: whatever" -H "Content-Type: application/json" http://localhost:3000/session.json
```

You get a 404 from doing this?

**Comment by mark100net** [comment]
@jwoertink Ok, I'm an idiot. My accept header was wrong (didn't realize the `vnd` part was literal).

It's working now. Thanks.

**Comment by jwoertink** [comment]
oh sweet! Yeah, it's literal, though I've thought about making that customized. So it's all good? If that's the case, then maybe I can just merge that in to master.

**Comment by mark100net** [comment]
@jwoertink Yes, please, merge away. I left this open just because there is still the issue with not supporting the current Rails version (don't forget to update so it can be bundled with 5.1.4). Thanks again.

**Comment by jwoertink** [comment]
sweet! 👍 Thanks for checking that out for me. I'll run one last test and then try and merge that this week. Unless you'd like to submit a PR? Either way, I'll have the master branch updated soonish.

**Comment by mark100net** [comment]
I'm happy to do a PR. What would you prefer to put as the upper limit on Rails version?

**Comment by mark100net** [comment]
One other thing I just noticed. This is a new app and I only had one controller originally. When I added a second one (in the same version), I see this when the Rails environment starts up:
```
/Users/markfraser/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/jko_api-eac106bac12b/lib/jko_api/class_descendants_builder.rb:71: warning: already initialized constant Api::V2
/Users/markfraser/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/jko_api-eac106bac12b/lib/jko_api/class_descendants_builder.rb:71: warning: previous definition of V2 was here
```

I don't have a V2 anywhere.

I verified that it goes away if I just delete the new controller.

I haven't seen any ill effects beyond the warning as of yet but I thought I would let you know.
